import Head from 'next/head';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
export default function Home() {
  const {push} = useRouter();

  useEffect(()=>{
    push('/home');
  },[])
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
